services:
  weibo-monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: WeiboForwarder
    image: weibo-forwarder:latest
    restart: unless-stopped
    volumes:
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - weibo-network
      - rsshub_default  # 连接到RSSHub网络
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs/weibo_monitor.log') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  weibo-network:
    driver: bridge
  rsshub_default:
    external: true  # 连接到已存在的RSSHub网络
